---
# tasks file for ez

- name: create the directory for the settings
  file:
    path: "{{ ez_local_settings_dir }}"
    state: directory
    mode: 0755

- name: touch the file and set the permissions
  file:
    path: "{{ ez_local_settings_dir }}/{{ ez_local_settings_file }}"
    state: touch
    mode: 0644

- name: include variables found in /etc/cyverse/ez.yml, if it exists; if error, just ignore
  include_vars:
    file: "{{ ez_local_settings_dir }}/{{ ez_local_settings_file }}"
  ignore_errors: yes

- name: logfile for ansible-pulls, let's touch it and set the right permissions
  file:
    path: "{{ ez_local_log }}"
    state: touch
    mode: 0777

# this section will install the python-cyverse-ez via pip; the package name collides with the existing pip, will rename later
- name: until the project has proper versions, for an uninstall of python-cyverse-ez
  pip:
    name: cyverse-ez
    state: absent

- name: install via pip
  pip:
    name: "{{ ez_python_cyverse_ez_url }}"
    state: forcereinstall
